services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=blog
    ports:
      - "5432:5432"
    volumes:
      - ./data-db/:/var/lib/postgresql/data/

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "paDlfJD6yGBtRZtFCNu2"
    volumes:
      - ./data-minio:/data
    command: server /data --console-address ":9001"

  api:
    image: blog-go-api
    container_name: blog-go-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:secret@postgres:5432/blog?sslmode=disable
      - ENVIRONMENT=development
      - HTTP_SERVER_ADDRESS=0.0.0.0:8080
      - GIN_MODE=release
      - URL_LOCALHOST=http://localhost:5173
      - TOKEN_SYMMETRIC_KEY=12345678901234567890123456789012
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY_ID=sTnvIE7zxv3T11dwuVdT
      - MINIO_SECRET_ACCESS_KEY=IENOZ7MJzi4Tpwn7ntiZd3zAOqUrOvRjI4qpXHxE
      - MINIO_USE_SSL=true
      - MINIO_BUCKET_NAME=blog
      - MINIO_URL_RESULT=http://localhost:9000/blog/
      - EMAIL_SENDER_NAME=sender_name
      - EMAIL_SENDER_ADDRESS=yourself@mail.com
      - EMAIL_SENDER_PASSWORD=yourselfpassword
