// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: permission_group.sql

package db

import (
	"context"
)

const getAllPermissionGroup = `-- name: GetAllPermissionGroup :many
SELECT 
id, name
FROM permission_group
`

func (q *Queries) GetAllPermissionGroup(ctx context.Context) ([]PermissionGroup, error) {
	rows, err := q.db.Query(ctx, getAllPermissionGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionGroup{}
	for rows.Next() {
		var i PermissionGroup
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
