// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAllBlog(ctx context.Context, lower string) (int64, error)
	CountAllBlogWithTag(ctx context.Context, arg CountAllBlogWithTagParams) (int64, error)
	CountAllRole(ctx context.Context, lower string) (int64, error)
	CountAllTag(ctx context.Context, lower string) (int64, error)
	CountUser(ctx context.Context) (int64, error)
	CountUserForGenerateCode(ctx context.Context) (int64, error)
	CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error)
	CreateBlogTag(ctx context.Context, arg CreateBlogTagParams) error
	CreateResetPassword(ctx context.Context, arg CreateResetPasswordParams) (ResetPassword, error)
	CreateRole(ctx context.Context, name string) (Role, error)
	CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) (RolePermission, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTag(ctx context.Context, name string) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserRole(ctx context.Context, arg CreateUserRoleParams) error
	DeleteBlog(ctx context.Context, id int64) error
	DeleteBlogTag(ctx context.Context, arg DeleteBlogTagParams) error
	DeleteBlogTagByBlogId(ctx context.Context, blogID int64) error
	DeleteRole(ctx context.Context, id int64) error
	DeleteRolePermission(ctx context.Context, arg DeleteRolePermissionParams) error
	DeleteRolePermissionByRoleId(ctx context.Context, roleID int64) error
	DeleteTag(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserRoleByUserId(ctx context.Context, userID int64) error
	// Queries to fix import errors in querier.go file
	// Please not use this queries for other purpose
	FixErrorImportPGType(ctx context.Context, dollar_1 pgtype.Timestamp) (interface{}, error)
	// Queries to fix import errors in querier.go file
	// Please not use this queries for other purpose
	FixErrorImportTime(ctx context.Context, createdAt time.Time) (int64, error)
	GetAllBlog(ctx context.Context, arg GetAllBlogParams) ([]GetAllBlogRow, error)
	GetAllBlogWithTag(ctx context.Context, arg GetAllBlogWithTagParams) ([]GetAllBlogWithTagRow, error)
	GetAllPermissionGroup(ctx context.Context) ([]PermissionGroup, error)
	GetAllRole(ctx context.Context, arg GetAllRoleParams) ([]GetAllRoleRow, error)
	GetAllTag(ctx context.Context, arg GetAllTagParams) ([]GetAllTagRow, error)
	GetBlogById(ctx context.Context, id int64) (GetBlogByIdRow, error)
	GetBlogByUrl(ctx context.Context, url string) (GetBlogByUrlRow, error)
	GetBlogTagByBlogId(ctx context.Context, blogID int64) ([]GetBlogTagByBlogIdRow, error)
	GetBlogTagByBlogIdAndTagId(ctx context.Context, arg GetBlogTagByBlogIdAndTagIdParams) (BlogTag, error)
	GetPermissionByPermissionGroupId(ctx context.Context, permissionGroupID int64) ([]GetPermissionByPermissionGroupIdRow, error)
	GetPermissionByPermissionGroupIdAndRoleId(ctx context.Context, arg GetPermissionByPermissionGroupIdAndRoleIdParams) ([]GetPermissionByPermissionGroupIdAndRoleIdRow, error)
	GetPermissionByUserId(ctx context.Context, id int64) ([]string, error)
	GetResetPasswordByToken(ctx context.Context, token string) (ResetPassword, error)
	GetRoleById(ctx context.Context, id int64) (GetRoleByIdRow, error)
	GetRoleByUserId(ctx context.Context, userID int64) ([]GetRoleByUserIdRow, error)
	GetRoleForDropDownList(ctx context.Context) ([]GetRoleForDropDownListRow, error)
	GetRolePermissionByRoleIdAndPermissionId(ctx context.Context, arg GetRolePermissionByRoleIdAndPermissionIdParams) (RolePermission, error)
	GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error)
	GetTagByCreatedAt(ctx context.Context, createdAt time.Time) ([]GetTagByCreatedAtRow, error)
	GetTagById(ctx context.Context, id int64) (GetTagByIdRow, error)
	GetUser(ctx context.Context, id int64) (GetUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserHashedPassword(ctx context.Context, id int64) (string, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	UpdateBlog(ctx context.Context, arg UpdateBlogParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UseResetPassword(ctx context.Context, token string) error
}

var _ Querier = (*Queries)(nil)
